version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sdp-mcp-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"  # Non-standard port to avoid conflicts
    environment:
      POSTGRES_USER: sdpmcpservice
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-*jDE1Bj%IPXKMe%Z}
      POSTGRES_DB: sdp_mcp
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database/migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sdpmcpservice -d sdp_mcp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sdp-mcp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: sdp-mcp-redis
    restart: unless-stopped
    ports:
      - "6380:6379"  # Non-standard port to avoid conflicts
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-R3d1s$3cur3P@ss}
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --appendonly yes
      --appendfsync everysec
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sdp-mcp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sdp-mcp-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@sdpmcp.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sdp-mcp-network
    profiles:
      - dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    name: sdp-mcp-postgres-data
  redis_data:
    name: sdp-mcp-redis-data
  pgadmin_data:
    name: sdp-mcp-pgadmin-data

networks:
  sdp-mcp-network:
    name: sdp-mcp-network
    driver: bridge